import type { SliderData } from '@/types/app';

const cdn = 'https://cdn.hanwei1234.com/Content/images';

export const CASINO_CLUB_SLIDER = [
	{
		disabled: true,
		front: `${cdn}/livecasino/ver2/club-ace-girl.png`,
		back: `${cdn}/livecasino/ver2/bg-club-ace.png`,
		header: `${cdn}/livecasino/ver2/ace-green`,
		description: 'club_ace_description',
		games: [],
		button1_link: '',
		button2_link: '',
	},
	{
		disabled: false,
		front: `${cdn}/livecasino/ver2/club-king-man.png`,
		back: `${cdn}/livecasino/ver2/bg-club-king.png`,
		header: `${cdn}/livecasino/ver2/king-green`,
		description: 'club_king_description',
		games: ['baccarat', 'roulette', 'sic_bo', 'dragon_tiger', 'fan_tan', 'lucky_spin'],
		button1_link: '/livecasino/clubking',
		button2_link: '/livecasino#clubking',
	},
	{
		disabled: false,
		front: `${cdn}/livecasino/ver2/club-queen-girl.png`,
		back: `${cdn}/livecasino/ver2/bg-club-queen.png`,
		header: `${cdn}/livecasino/ver2/queen-green`,
		description: 'club_king_description',
		games: ['baccarat', 'roulette', 'sic_bo', 'dragon_tiger', 'black_jack', 'win_3cards'],
		button1_link: '/livecasino/clubqueen',
		button2_link: '/livecasino#clubqueen',
	},
	{
		disabled: false,
		front: `${cdn}/livecasino/ver2/club-jack-man.png`,
		back: `${cdn}/livecasino/ver2/bg-club-jack.png`,
		header: `${cdn}/livecasino/ver2/jack-green`,
		description: 'club_jack_description',
		games: ['baccarat', 'roulette', 'sic_bo', 'dragon_tiger', 'bull_bull', 'win_3cards'],
		button1_link: '/livecasino/clubjack',
		button2_link: '/livecasino#clubjack',
	},
	{
		disabled: true,
		front: `${cdn}/livecasino/ver2/club-ten-girl.png`,
		back: `${cdn}/livecasino/ver2/bg-club-ten.png`,
		header: `${cdn}/livecasino/ver2/ten-green`,
		description: 'club_ten_description',
		options: [],
		button1_link: '',
		button2_link: '',
	},
	{
		disabled: false,
		front: `${cdn}/livecasino/ver2/club-nine-girl.png`,
		back: `${cdn}/livecasino/ver2/bg-club-nine.png`,
		header: `${cdn}/livecasino/ver2/nine-green`,
		description: 'club_nine_description',
		games: ['baccarat', 'roulette', 'sic_bo', 'dragon_tiger', 'bull_bull'],
		button1_link: '/livecasino/clubnine',
		button2_link: '/livecasino#clubnine',
	},
	{
		disabled: false,
		front: `${cdn}/livecasino/ver2/club-eight-girl.png`,
		back: '',
		header: `${cdn}/livecasino/ver2/eight-green`,
		description: 'club_eight_description',
		games: [
			'baccarat',
			'roulette',
			'sic_bo',
			'dragon_tiger',
			'bull_bull',
			'craps',
			'dream_catcher',
			'mega_ball',
			'lightning_dice',
			'casino_holdem',
		],
		button1_link: '/livecasino/clubeight',
		button2_link: '/livecasino#clubeight',
	},
];

export const LIVE_CASINO_SLIDER: SliderData[] = [
	{
		title: 'live_casino1',
		textPosition: 'right',
		webBg: `${cdn}/slider/live-casino/web-casino-live-casino`,
		webText: '',
		btnLabel: 'bet_now',
		btnLink: '/livecasino/ClubEight',
		mobile: `${cdn}/slider/live-casino/mobile-casino-live-casino.webp`,
	},
	{
		title: 'live_casino2',
		textPosition: 'right',
		webBg: `${cdn}/slider/blockchain-baccarat/web-casino-baccarat-2023`,
		webText: '',
		btnLabel: 'bet_now',
		btnLink: '/livecasino/ClubQueen',
		mobile: `${cdn}/slider/blockchain-baccarat/mobile-casino-baccarat-2023.webp`,
	},
	{
		title: 'live_casino3',
		textPosition: 'right',
		webBg: `${cdn}/slider/blackjack/web-blackjack-club8-2023`,
		webText: '',
		btnLabel: 'bet_now',
		btnLink: '/livecasino/ClubQueen',
		mobile: `${cdn}/slider/blackjack/mobile-blackjack-club8-2023.webp`,
	},
	{
		title: 'live_casino5',
		textPosition: 'right',
		webBg: `${cdn}/slider/live-casino-rebate/web-livecasino-rebate`,
		webText: '',
		btnLabel: 'bet_now',
		btnLink: '/promotions',
		mobile: `${cdn}/slider/live-casino-rebate/mobile-livecasino-rebate.webp`,
	},
];

export const LIVE_CASINO_CARDS = [
	{
		label: 'live_casino1',
		image: `${cdn}/livecasino/ClubThumbnails/club-king-girl-v2.png`,
		imageXoffset: 18,
		imageWidth: 304,
		text: `${cdn}/livecasino/ClubThumbnails/ClubKing-Text`,
		playLink: '/livecasino/ClubKing',
		infoLink: '/livecasino',
	},
	{
		label: 'live_casino2',
		image: `${cdn}/livecasino/ClubThumbnails/club-queen-girl-v2.png`,
		imageXoffset: 56,
		imageWidth: 212,
		text: `${cdn}/livecasino/ClubThumbnails/ClubQueen-Text`,
		playLink: '/livecasino/ClubQueen',
		infoLink: '/livecasino',
	},
	{
		label: 'live_casino3',
		image: `${cdn}/livecasino/ClubThumbnails/club-jack-girl-v2.png`,
		imageXoffset: 14,
		imageWidth: 328,
		text: `${cdn}/livecasino/ClubThumbnails/ClubJack-Text`,
		playLink: '/livecasino/ClubJack',
		infoLink: '/livecasino',
	},
	{
		label: 'live_casino4',
		image: `${cdn}/livecasino/ClubThumbnails/club-nine-girl-v2.png`,
		imageXoffset: 30,
		imageWidth: 250,
		text: `${cdn}/livecasino/ClubThumbnails/ClubNine-Text`,
		playLink: '/livecasino/ClubNine',
		infoLink: '/livecasino',
	},
	{
		label: 'live_casino5',
		image: `${cdn}/livecasino/ClubThumbnails/club-eight-girl-v2.png`,
		imageXoffset: 20,
		imageWidth: 312,
		text: `${cdn}/livecasino/ClubThumbnails/ClubEight-Text`,
		playLink: '/livecasino/ClubEight',
		infoLink: '/livecasino',
	},
];

export const CASINO_TOP_WINNERS = [
	{
		image: `${cdn}/livecasino/TopWinners/club_king_roulette1.jpg`,
		game: 'Club King Roulette 10',
		player: 'ac**bi***n',
		amount: '765,333',
	},
	{
		image: `${cdn}/livecasino/TopWinners/club_ace_baccarat8_1.jpg`,
		game: 'Club Queen Baccarat 6',
		player: '***3o**Ty*',
		amount: '18,000,789',
	},
	{
		image: `${cdn}/livecasino/TopWinners/club_ace_roulette.jpg`,
		game: 'Club Ace Roulette 1',
		player: 'ed**4****',
		amount: '23,888,696',
	},
	{
		image: `${cdn}/livecasino/TopWinners/club_king_baccarat3.jpg`,
		game: 'Club King Baccarat 1',
		player: 'yah***81**',
		amount: '120,111,000',
	},
	{
		image: `${cdn}/livecasino/TopWinners/club_king_roulette1.jpg`,
		game: 'Club King Roulette 6',
		player: 'e**tn**84**',
		amount: '3,488,789',
	},
	{
		image: `${cdn}/livecasino/TopWinners/club_king_roulette1.jpg`,
		game: 'Club King Roulette 16',
		player: 'ali**b**a',
		amount: '897,256',
	},
	{
		image: `${cdn}/livecasino/TopWinners/club_ace_baccarat1.jpg`,
		game: 'Club Ace Baccarat 1',
		player: 's****8*01',
		amount: '12,451,700',
	},
	{
		image: `${cdn}/livecasino/TopWinners/club_jack_baccarat1_1.jpg`,
		game: 'Club Jack Baccarat 4',
		player: '***er**5*67**',
		amount: '9,000,000',
	},
];
