#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"


cd ../main-client-membersite 
NODE_VERSION=`cat .nvmrc`
nvm use "$NODE_VERSION"
pnpm lint-staged