export const CASINO_SECTIONS_EN = [
	{
		sectionClassNames: ['subMenu__subSectionCasinoTop'],
		wrapperClassNames: ['subMenu__contentWrapperCasinoTop'],
		contentClassNames: ['subMenu__sectionContentCasinoTop'],
		linkProps: [
			{ href: '/casinoclub/ClubAce', target: '_blank' },
			{ href: '/casinoclub/ClubKing', target: '_blank' },
			{ href: '/casinoclub/ClubQueen', target: '_blank' },
			{ href: '/casinoclub/ClubJack', target: '_blank' },
			{ href: '/casinoclub/ClubTen', target: '_blank' },
		],
		hovClassNames: [
			'subMenu__subHovClubA',
			'subMenu__subHovClubK',
			'subMenu__subHovClubQ',
			'subMenu__subHovClubJ',
			'subMenu__subHovClubT',
		],
		menuClassNames: [
			'subMenu__casinoMenuClubA',
			'subMenu__casinoMenuClubK',
			'subMenu__casinoMenuClubQ',
			'subMenu__casinoMenuClubJ',
			'subMenu__casinoMenuClubT',
		],
		spanClassNames: [
			'subMenu__clubAce',
			'subMenu__clubKing',
			'subMenu__clubQueen',
			'subMenu__clubJack',
			'subMenu__clubTen',
		],
		subName: [
			'sub_menu.casino_club_a',
			'sub_menu.casino_club_k',
			'sub_menu.casino_club_q',
			'sub_menu.casino_club_j',
			'sub_menu.casino_club_10',
		],
		subNameClassNames: ['subMenu__subName'],
		playClassNames: [
			'subMenu__subPlayClubA',
			'subMenu__subPlayClubK',
			'subMenu__subPlayClubQ',
			'subMenu__subPlayClubJ',
			'subMenu__subPlayClubT',
		],
		playText: [
			'sub_menu.casino_play_now',
			'sub_menu.casino_play_now',
			'sub_menu.casino_play_now',
			'sub_menu.casino_play_now',
			'sub_menu.casino_play_now',
		],
	},
	{
		sectionClassNames: ['subMenu__subSectionCasinoBottom'],
		wrapperClassNames: ['subMenu__contentWrapperCasinoTop'],
		contentClassNames: ['subMenu__sectionContentCasinoTop'],
		linkProps: [
			{ href: '/casinoclub/ClubNine', target: '_blank' },
			{ href: '/casinoclub/ClubEight', target: '_blank' },
		],
		hovClassNames: ['subMenu__subHovClubN', 'subMenu__subHovClubE'],
		menuClassNames: ['subMenu__casinoMenuClubN', 'subMenu__casinoMenuClubE'],
		spanClassNames: ['subMenu__clubNine', 'subMenu__clubEight'],
		newSubName: [{ 'sub_menu.casino_club_8': 'sub_menu.casino_new' }],
		newClassNames: ['subMenu__subNameClubENew'],
		subName: ['sub_menu.casino_club_9', 'sub_menu.casino_club_8'],
		subNameClassNames: ['subMenu__subName'],
		playClassNames: ['subMenu__subPlayClubN', 'subMenu__subPlayClubE'],
		playText: ['sub_menu.casino_play_now', 'sub_menu.casino_play_now'],
	},
];
